version: '3.7'

services:
  app:
    enviroment:
      - FLASK_ENV=development
    volumes:
      - ./blog:/app
    build: ./blog
    container_name: 'blogzin'
    ports:
      - "5000:5000"
